// Code generated by cmd/wiregen -upstream 40c75256f4c082b0e0d4310fbbb7ddce19a8d430; DO NOT EDIT.
// Source: backend/internal/registry/testdata/upstream/freebuff-models.ts
// (plus freebuff-model-ids.ts, freebuff-model-entitlements.ts, model-config.ts)
// at upstream commit 40c75256f4c082b0e0d4310fbbb7ddce19a8d430.
package modelcat

import (
	"strings"
	"time"
)

// ModelInfo describes one catalog model and every proxy fact about it.
type ModelInfo struct {
	// ID is the wire model id (provider/model).
	ID string
	// DisplayName is the upstream catalog display name (used in the
	// withdrawn-model refusal copy, mirroring freebuffWithdrawnModelMessage).
	DisplayName string
	// Served gates /v1/models and the chat handlers: the ids this gateway
	// serves or advertises. Paused models are never Served.
	Served bool
	// Tiers lists the upstream tier sets that admit this row, in canonical
	// order TierLimited, TierFull, TierPaid, TierOffer. Nil when no tier
	// offers it (withdrawn and god-only rows), never a partial order.
	Tiers []string
	// PausedReplacement is non-empty exactly when upstream
	// FREEBUFF_PAUSED_FREE_MODEL_IDS lists the model: recognized but
	// admission-refused. It names the model the refusal copy recommends.
	PausedReplacement string
	// Premium marks FREEBUFF_PREMIUM_MODEL_IDS membership (the shared daily
	// premium pool). Fable 5.1 is premium-flagged upstream but metered by its
	// own global pool (FREEBUFF_LIMITED_OFFER_MODEL_IDS), not the shared
	// pool, so it is NOT marked Premium here.
	Premium bool
	// PlanRequired marks FREEBUFF_PRO_ONLY_EVERY_SURFACE_MODEL_IDS membership:
	// a paid plan is required and the upstream server refuses the admission on
	// every surface. The picker draws the row locked (PlanRequiredLabel, no
	// price) instead of hiding it, so a client can see what a plan buys.
	PlanRequired bool
	// Experimental mirrors upstream FreebuffModelOption.experimental (the BETA
	// badge): the row stays user-pickable but is never the automatic default
	// (auto-touch, smoke probe, session fallback), because an anonymous host
	// can reprice, rename or withdraw it without notice.
	Experimental bool
	// ContextWindow mirrors FREEBUFF_MODEL_CONTEXT_WINDOWS in tokens; 0
	// means upstream falls back to DefaultContextWindow.
	ContextWindow int
	// Efforts is the upstream reasoning-effort ladder (nil = route accepts
	// and ignores reasoning_effort, so conversion uses the default ladder).
	Efforts []string
	// Tagline is the upstream catalog description (used in picker & catalog).
	Tagline string
	// TaglineTooltip mirrors upstream FreebuffModelOption.taglineTooltip:
	// the row tooltip the CLI shows next to the tagline. Empty when upstream
	// carries no string literal for the row.
	TaglineTooltip string
	// Notice is the upstream warning or special offer (e.g. AI training, promo).
	Notice string
	// Badges are the capability/freshness chips (e.g. Reasoning: max*, Images, NEW).
	Badges []string
}

// Catalog is the full free-catalog table, in upstream SUPPORTED_FREEBUFF_MODELS
// order.
var Catalog = []ModelInfo{
	{ID: "stealth/ox-alpha", DisplayName: "Ox Alpha",
		ContextWindow:     1000000,
		Efforts:           []string{"low", "high", "max"},
		PausedReplacement: "z-ai/glm-5.3-flash"},
	{ID: "stealth/space-bunny-alpha", DisplayName: "Space Bunny Alpha",
		Tagline:        "1M context",
		TaglineTooltip: "A stealth model from an anonymous provider. It may change or be withdrawn without notice.",
		Badges:         []string{"Reasoning: high", "Images", "NEW"},
		Notice:         "Anonymous provider retains prompts",
		Served:         true,
		Tiers:          []string{TierFull},
		ContextWindow:  1000000,
		Efforts:        []string{"low", "medium", "high", "xhigh", "max"},
		Experimental:   true},
	{ID: "deepseek/deepseek-v4-pro", DisplayName: "DeepSeek V4 Pro",
		ContextWindow:     1048576,
		Efforts:           []string{"low", "high", "max"},
		PausedReplacement: "z-ai/glm-5.3-flash"},
	{ID: "minimax/minimax-m3", DisplayName: "MiniMax M3",
		ContextWindow:     524288,
		Efforts:           []string{"high"},
		PausedReplacement: "z-ai/glm-5.3-flash"},
	{ID: "openai/gpt-5.6-luna", DisplayName: "GPT-5.6 Luna",
		Tagline:       "Strong all-around",
		Badges:        []string{"Reasoning: high", "Images"},
		ContextWindow: 1000000,
		Efforts:       []string{"low", "medium", "high", "xhigh", "max"}},
	{ID: "openai/gpt-6-luna", DisplayName: "GPT-6 Luna",
		Tagline:        "Strong all-around",
		TaglineTooltip: "Runs on OpenAI flex capacity: half the token price, the same speed in our measurements, and a standard-tier backup when flex is busy.",
		Badges:         []string{"Reasoning: high", "Images", "NEW"},
		Served:         true,
		Tiers:          []string{TierFull, TierPaid},
		Premium:        true,
		ContextWindow:  1000000,
		Efforts:        []string{"low", "medium", "high", "xhigh", "max"},
		Experimental:   true},
	{ID: "upstage/solar-pro4", DisplayName: "Solar Pro 4",
		Tagline:       "0 Freebucks",
		ContextWindow: 500000},
	{ID: "upstage/solar-mini4", DisplayName: "Solar Mini 4",
		Tagline:       "Fast and light",
		Badges:        []string{"NEW"},
		Served:        true,
		Tiers:         []string{TierLimited, TierFull},
		ContextWindow: 500000},
	{ID: "google/gemini-3.8-flash", DisplayName: "Gemini 3.8 Flash",
		Tagline:      "1M context",
		Badges:       []string{"Images", "NEW"},
		Tiers:        []string{TierFull, TierPaid},
		Efforts:      []string{"low", "medium", "high", "xhigh", "max"},
		PlanRequired: true},
	{ID: "meta/muse-spark-1.3-contributor", DisplayName: "Muse Spark 1.3",
		Tagline:           "Queues, then falls back",
		Badges:            []string{"Reasoning: xhigh", "NEW"},
		Notice:            "May use data for AI training",
		ContextWindow:     1000000,
		Efforts:           []string{"minimal", "low", "medium", "high", "xhigh"},
		PausedReplacement: "z-ai/glm-5.3-flash"},
	{ID: "meta/muse-spark-1.2-contributor", DisplayName: "Muse Spark 1.2",
		Tagline:       "Queue",
		Badges:        []string{"Reasoning: xhigh"},
		Notice:        "May use data for AI training",
		Served:        true,
		Tiers:         []string{TierFull},
		Premium:       true,
		ContextWindow: 1000000,
		Efforts:       []string{"minimal", "low", "medium", "high", "xhigh"}},
	{ID: "z-ai/glm-5.2", DisplayName: "GLM 5.2",
		Tagline:           "Referral reward",
		Badges:            []string{"Referral only"},
		Notice:            "Unlocked via referral code",
		PausedReplacement: "z-ai/glm-5.3-flash"},
	{ID: "z-ai/glm-5.3-flash", DisplayName: "GLM 5.3 Flash",
		Tagline:       "Deep reasoning",
		Badges:        []string{"Reasoning: max*", "Images", "NEW"},
		Served:        true,
		Tiers:         []string{TierLimited, TierFull, TierPaid},
		ContextWindow: 1000000,
		Efforts:       []string{"low", "high", "max"}},
	{ID: "deepseek/deepseek-v4-flash", DisplayName: "DeepSeek V4.1 Flash",
		Tagline:       "Smart & Fast",
		Badges:        []string{"Reasoning: high", "Images", "NEW"},
		Notice:        "May use data for AI training",
		Served:        true,
		Tiers:         []string{TierLimited, TierFull, TierPaid},
		ContextWindow: 1048576,
		Efforts:       []string{"low", "high", "max"}},
	{ID: "mimo/mimo-v2.5", DisplayName: "MiMo 2.6 Flash",
		Tagline: "Balanced",
		Badges:  []string{"Images", "NEW"},
		Served:  true,
		Tiers:   []string{TierLimited, TierFull},
		Efforts: []string{"high"}},
	{ID: "mimo/mimo-v2.6-pro", DisplayName: "MiMo 2.6 Pro",
		Tagline:      "Strong reasoning",
		Badges:       []string{"Images", "NEW"},
		Tiers:        []string{TierFull, TierPaid},
		PlanRequired: true},
	{ID: "anthropic/claude-fable-5.1", DisplayName: "Claude Fable 5.1",
		Tiers:   []string{TierOffer},
		Efforts: []string{"low", "medium", "high", "xhigh", "max"}},
}

// DefaultModelID mirrors upstream DEFAULT_FREEBUFF_MODEL_ID
// (FREEBUFF_MODELS[0]): what the upstream CLI resolves a blank model pick
// to, and what paused-model refusals recommend.
const DefaultModelID = "z-ai/glm-5.3-flash"

// FallbackModelID mirrors upstream FALLBACK_FREEBUFF_MODEL_ID: the model
// guaranteed available on EVERY tier that unavailable picks are coerced to.
const FallbackModelID = "mimo/mimo-v2.5"

// LimitedModelID is the proxy limited-tier admission row: the unlimited
// fallback row, pinned to FALLBACK (not to upstream LIMITED_FREEBUFF_MODEL_ID,
// which upstream split from the picker hero on 2026-09-07 into a coercion
// target of its own). The server gate admits only this row without quota, so
// following upstream here would widen limited-tier admission; revisit
// deliberately, never on sync.
const LimitedModelID = "mimo/mimo-v2.5"

// PlanRequiredLabel / PlanRequiredLine mirror upstream
// FREEBUFF_PLAN_REQUIRED_LABEL and FREEBUFF_PLAN_REQUIRED_LINE
// (common/src/util/freebuff-model-selection.ts): the locked row's badge and
// sentence, the same copy the CLI prints.
const (
	PlanRequiredLabel = "Paid plan"
	PlanRequiredLine  = "Included with a paid plan."
)

// SubscriptionProModelIDs mirrors upstream FREEBUFF_SUBSCRIPTION_PRO_MODEL_IDS,
// the freebuff-subscriptions.ts name for FREEBUFF_PRO_ONLY_CATALOG_MODEL_IDS: the
// static paid-session boundary a viewer with no server verdict falls back to.
// It is NOT the every-surface refusal set (ModelInfo.PlanRequired /
// FREEBUFF_PRO_ONLY_EVERY_SURFACE_MODEL_IDS): GPT-6 Luna is listed here but
// carries a US exemption, so the server does not refuse it on every surface.
var SubscriptionProModelIDs = []string{"google/gemini-3.8-flash", "mimo/mimo-v2.6-pro", "openai/gpt-6-luna"}

// IsSubscriptionPro mirrors upstream isFreebuffSubscriptionProModelId:
// suffix-tolerant, so a dated provider snapshot (mimo-mimo-v2.6-pro-<date>)
// cannot dodge the plan gate.
func IsSubscriptionPro(id string) bool {
	for _, pro := range SubscriptionProModelIDs {
		if id == pro || strings.HasPrefix(id, pro+"-") {
			return true
		}
	}
	return false
}

// DeepSeekV4FlashModelID mirrors upstream FREEBUFF_DEEPSEEK_V4_FLASH_MODEL_ID.
const DeepSeekV4FlashModelID = "deepseek/deepseek-v4-flash"

// LimitedTierModelIDs mirrors upstream LIMITED_FREEBUFF_MODEL_IDS: the four models
// available to limited-access tier accounts (GLM 5.3 Flash, DeepSeek V4 Flash,
// MiMo 2.6 Flash — the wire id keeps its v2.5 spelling —, Solar Mini 4, which
// took Solar Pro 4's slot on 2026-09-23).
var LimitedTierModelIDs = []string{
	Glm53ModelID,
	DeepSeekV4FlashModelID,
	LimitedModelID,
	SolarMini4ModelID,
}

// IsLimitedTierAllowed reports whether the model is available on the limited tier
// without requiring special referral grants (matches upstream LIMITED_FREEBUFF_MODEL_IDS).
func IsLimitedTierAllowed(id string) bool {
	switch id {
	case Glm53ModelID, DeepSeekV4FlashModelID, LimitedModelID, SolarMini4ModelID:
		return true
	default:
		return false
	}
}

// Glm52ModelID is the referral-reward model, metered by its own promo pool
// rather than the shared premium pool.
const Glm52ModelID = "z-ai/glm-5.2"

// Glm53ModelID is the unmetered standard row and the proxy default.
const Glm53ModelID = "z-ai/glm-5.3-flash"

// SolarMini4ModelID mirrors FREEBUFF_SOLAR_MINI_4_MODEL_ID: the Upstage row
// that took Solar Pro 4's slot on every surface on 2026-09-23, unmetered at
// full access (entitlement fullAccess.premium=false) and offered at limited
// access.
const SolarMini4ModelID = "upstage/solar-mini4"

// SolarPro4ModelID mirrors FREEBUFF_SOLAR_PRO_4_MODEL_ID: RETIRED from every
// picker on 2026-09-23 (superseded by Solar Mini 4) but still SUPPORTED and
// admissible, so sessions admitted before the swap drain and released
// binaries keep working. Kept for the retired-row pins; new picks use
// SolarMini4ModelID.
const SolarPro4ModelID = "upstage/solar-pro4"

// GLMSessionLength mirrors upstream FREEBUFF_REWARD_SESSION_LENGTH_MS (the
// earned-reward session pool GLM 5.2 admits from; the older
// FREEBUFF_GLM_V52_SESSION_LENGTH_MS name is gone upstream): GLM sessions
// are exactly one hour of wall-clock time.
const GLMSessionLength = time.Hour

// DefaultContextWindow mirrors upstream FREEBUFF_DEFAULT_CONTEXT_WINDOW:
// assumed for any model absent from FREEBUFF_MODEL_CONTEXT_WINDOWS.
const DefaultContextWindow = 131072
