// Code generated by cmd/wiregen -upstream e2b911eca949054b11f590227010527be467369e; DO NOT EDIT.
// Snapshots: backend/internal/wirefacts/testdata/wire/snapshots.json at
// upstream commit e2b911eca949054b11f590227010527be467369e (npm freebuff 0.0.178).
package wirefacts

// UpstreamSHA is the upstream commit the snapshots were taken from.
const UpstreamSHA = "e2b911eca949054b11f590227010527be467369e"

// VendorVersion is the npm freebuff wrapper version recorded alongside.
const VendorVersion = "0.0.178"

// WireFiles lists the verbatim upstream wire snapshots.
var WireFiles = []WireFile{
	{Path: "common/src/constants/freebuff-standing.ts", SHA256: "555339c61867c8201bca066765f8b4497b874e62a142be9f2d30996d46b3fb32"},
	{Path: "common/src/constants/foreign-client-signals.ts", SHA256: "505f9b42af1758b5403233737251b231a9369a312dbe4dcde6ceeed538589da9"},
	{Path: "common/src/constants/freebuff-spend-ceilings.ts", SHA256: "5f40df1b178c6248a8f190fb467f8adc5a4bbbe06032711ca4e3d1dfa8dbe2ea"},
	{Path: "common/src/constants/freebuff-signup-block.ts", SHA256: "b4200624750273c214c5648bd5caf23724d7e77205423aed28e162cefb7fb771"},
	{Path: "common/src/constants/freebuff-peak-hours.ts", SHA256: "8cb33dfeaf178acfd1bc8048f51b7a05962f3baca407596078daf67f70a8daea"},
	{Path: "common/src/util/freebuff-model-availability.ts", SHA256: "b7434b7920faf7e7f40f3ba535fc70f43a5672f218f6563dfdf2505e62ef151c"},
	{Path: "cli/src/components/freebuff-model-selector.tsx", SHA256: "e12cce35c23b1da006ce560d7016b92ad8f1a6417b86baf91fe985ad37ea5428"},
	{Path: "common/src/types/freebuff-session.ts", SHA256: "ad5273cde2ca87b0823f1c9bd202fb624cb49b87eadb0c50e6089f48220f2c51"},
	{Path: "packages/agent-runtime/src/constants.ts", SHA256: "233ab67d19223467f665ecaa085e732d0ee478740b6bc469e029598392d949e4"},
	{Path: "packages/agent-runtime/src/prompt-agent-stream.ts", SHA256: "7bf7ca49fb51ee52e340e577c999fd8e1a402602971f5d09897c831c444eb55f"},
	{Path: "packages/agent-runtime/src/run-agent-step.ts", SHA256: "b6d85d39947fa10726590e473cbe4708879d4946b5aa648be1498abaee40416c"},
	{Path: "packages/agent-runtime/src/run-programmatic-step.ts", SHA256: "74c336651c7ebac174714f67df821e6a3ce509edbcf769e7e8a6063a7e215be8"},
	{Path: "common/src/tools/constants.ts", SHA256: "c2508c4590f2b8dacf72075d32a0f21099037cb4cf3a37b097fafd670bf110b9"},
}

// RegistryPins lists the registry mirror files verified with the snapshots.
var RegistryPins = []WireFile{
	{Path: "free-agents.ts", SHA256: "35c666a7316b58af12b5d68e2ed782bc8d9a933c3344565190ce9377b01f5a7c"},
	{Path: "freebuff-model-ids.ts", SHA256: "b4a0f2aca8ea66c1d2dcbba74003f310fd95185e60839a560115068c4493409b"},
	{Path: "freebuff-models.ts", SHA256: "6d60bada811097941e7a334c03347d372f54104254c9ba3975952fce7610d171"},
	{Path: "gemini.ts", SHA256: "5de5784f96331b93cccd7a4356af17de52783f1727acee17f9c5ebe390569e80"},
	{Path: "model-config.ts", SHA256: "210f9bbfe1ac249aafeb0b134c01c2725b491696130313d225803290f0b988ea"},
	{Path: "freebuff-model-entitlements.ts", SHA256: "695bf9dd0c8d50937fbd01fd127631ef4cced7427cc1595c44476d84d2fc43cb"},
}
