package convert

import (
	"encoding/json"
	"os"
	"regexp"
	"strings"
	"testing"
)

// Corpus-driven tool-name coverage (issue #685).
//
// toolmap_coverage_test.go holds the CURATED table of hand-researched client
// tool names; this file is its corpus twin. The fixture
// testdata/tool_calls_corpus.json is generated by
// scripts/extract-tool-calls.sh from the (gitignored, CI-absent) reference/
// corpus of agent CLIs and harnesses — every model-facing tool name each
// harness registers, with the registry file that declares it. The test never
// reads reference/ itself, so it stays hermetic.
//
// For each harness the fixture's full tool list is replayed through the real
// ingress→egress path (NormalizeRequestMapped, then both upstream response
// shapes) and the wire is checked against the four contract invariants:
//
//  1. wire names are unique — strict upstreams (DeepSeek, Muse Spark, MiMo)
//     reject duplicate tool names outright ("Tool names must be unique"), so
//     dedupe is unconditional;
//  2. no wire name is a member of ForeignHarnessToolNames — upstream's
//     detector raises foreign_tool_names on ANY harness name, enforced;
//  3. every wire name restores through RestoreName to the EXACT client name
//     (case and spelling preserved), and FromUpstreamChunk agrees for both
//     choices[].delta.tool_calls[] and choices[].message.tool_calls[];
//  4. ClassifyWireTools still reads first-party: at least one GENUINE
//     signature tool and no enforced foreign signal.
//
// Invariants 2 and 3 are checked per CLIENT tool by wire index: ToUpstream
// walks tools[] in order and only APPENDS the injected end_turn/decide, so the
// check loop covers exactly the client's own tools and never the injections
// (invariant 1 scans the whole array, injections included).
//
// A failure here is a real harness-tool regression: the message names the
// harness, the client tool, the wire name and the registry source the fixture
// recorded for that tool, so the offending registry line is one grep away.

// corpusFixture mirrors testdata/tool_calls_corpus.json, written by
// scripts/extract-tool-calls.sh. Keys and order are pinned by the generator.
type corpusFixture struct {
	Source      string          `json:"source"`
	GeneratedBy string          `json:"generated_by"`
	Harnesses   []corpusHarness `json:"harnesses"`
}

// corpusHarness is one harness repo's extracted model-facing tool registry.
type corpusHarness struct {
	Harness string       `json:"harness"`
	Repo    string       `json:"repo"`
	Notes   string       `json:"notes"`
	Tools   []corpusTool `json:"tools"`
}

// corpusTool is one extracted tool name plus the registry file:line that
// declares it (repo-relative), quoted verbatim in failure messages.
type corpusTool struct {
	Name   string `json:"name"`
	Source string `json:"source"`
}

const corpusFixturePath = "testdata/tool_calls_corpus.json"

// corpusInjectedTools are appended by normalizeToolSchemas rather than sent by
// the client, so they are skipped by the per-tool invariants (see the file
// header).
var corpusInjectedTools = map[string]bool{"end_turn": true, "decide": true}

// corpusPlaceholderNames are fixture-poison: names that only appear in
// examples, test fixtures or README snippets. Their presence means the
// extractor stopped reading a registry and started reading prose.
var corpusPlaceholderNames = map[string]bool{
	"foo": true, "bar": true, "baz": true,
	"test_tool": true, "my_tool": true, "example_tool": true,
}

func loadCorpusFixture(t *testing.T) corpusFixture {
	t.Helper()
	raw, err := os.ReadFile(corpusFixturePath)
	if err != nil {
		t.Fatalf("read %s (regenerate with scripts/extract-tool-calls.sh): %v", corpusFixturePath, err)
	}
	var fx corpusFixture
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("parse %s: %v", corpusFixturePath, err)
	}
	return fx
}

// corpusClientTool renders one fixture tool as an OpenAI function tool with a
// plausible single-property object schema, so the normalizer's schema path
// (normalizeToolSchemas + the schema cache) actually runs on it.
func corpusClientTool(name string) map[string]any {
	return map[string]any{
		"type": "function",
		"function": map[string]any{
			"name":        name,
			"description": "Corpus tool " + name,
			"parameters": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"input": map[string]any{"type": "string", "description": "Tool input"},
				},
				"required": []any{"input"},
			},
		},
	}
}

// corpusWireName reads the function name out of one wire tool entry.
func corpusWireName(tool any) string {
	fn, ok := tool.(map[string]any)["function"].(map[string]any)
	if !ok {
		return ""
	}
	name, _ := fn["name"].(string)
	return name
}

// corpusRoundTripChunk pushes one wire tool name through
// ToolMapper.FromUpstreamChunk in the given shape and returns the name the
// client sees. Both relay shapes (streaming delta and non-streaming message)
// must agree with RestoreName — the mapper is only correct if all three
// restore paths return the same client name.
func corpusRoundTripChunk(mapper ToolMapper, shape, wire string) string {
	call := map[string]any{
		"index":    0,
		"id":       "call_corpus",
		"type":     "function",
		"function": map[string]any{"name": wire, "arguments": "{}"},
	}
	choice := map[string]any{"index": 0, "finish_reason": "tool_calls"}
	switch shape {
	case "delta":
		choice["delta"] = map[string]any{"tool_calls": []any{call}}
	case "message":
		choice["message"] = map[string]any{"tool_calls": []any{call}}
	default:
		panic("unknown chunk shape " + shape)
	}
	chunk := map[string]any{"choices": []any{choice}}
	mapper.FromUpstreamChunk(chunk)
	tcs, _ := choice[shape].(map[string]any)["tool_calls"].([]any)
	fn, _ := tcs[0].(map[string]any)["function"].(map[string]any)
	name, _ := fn["name"].(string)
	return name
}

// corpusNormalize runs one fixture harness's tool list through the mapped
// ingress path and returns the wire tools plus the mapper.
func corpusNormalize(t *testing.T, h corpusHarness) ([]any, ToolMapper) {
	t.Helper()
	if len(h.Tools) == 0 {
		t.Fatalf("harness %s: fixture carries no tools (the extractor must fail loudly rather than emit an empty harness)", h.Harness)
	}
	tools := make([]any, 0, len(h.Tools))
	for _, ct := range h.Tools {
		tools = append(tools, corpusClientTool(ct.Name))
	}
	body, err := json.Marshal(map[string]any{
		"model":    "deepseek/deepseek-v4-flash",
		"messages": []any{map[string]any{"role": "user", "content": "hi"}},
		"tools":    tools,
	})
	if err != nil {
		t.Fatalf("harness %s: marshal request: %v", h.Harness, err)
	}
	norm, mapper, err := NormalizeRequestMapped(body, "")
	if err != nil {
		t.Fatalf("harness %s: NormalizeRequestMapped: %v", h.Harness, err)
	}
	var parsed map[string]any
	if err := json.Unmarshal(norm, &parsed); err != nil {
		t.Fatalf("harness %s: unmarshal normalized: %v", h.Harness, err)
	}
	wireTools, ok := parsed["tools"].([]any)
	if !ok || len(wireTools) < len(tools) {
		t.Fatalf("harness %s: wire tools = %v, want at least the %d client tools plus the injected signature tools", h.Harness, parsed["tools"], len(tools))
	}
	return wireTools, mapper
}

// TestCorpusToolNameMapping is the corpus sweep: one request per harness repo,
// every registry-declared tool name in it, checked against the four contract
// invariants.
func TestCorpusToolNameMapping(t *testing.T) {
	fx := loadCorpusFixture(t)

	harnesses, names := 0, 0
	for _, h := range fx.Harnesses {
		harnesses++
		names += len(h.Tools)
	}
	if harnesses == 0 || names == 0 {
		t.Fatalf("fixture %s covers %d harnesses / %d tool names: regenerate it with scripts/extract-tool-calls.sh", corpusFixturePath, harnesses, names)
	}

	for _, h := range fx.Harnesses {
		t.Run(h.Harness, func(t *testing.T) {
			assertCorpusHarnessWireClean(t, h)
		})
	}
	t.Logf("corpus sweep: %d harnesses, %d model-facing tool names", harnesses, names)
}

func assertCorpusHarnessWireClean(t *testing.T, h corpusHarness) {
	t.Helper()
	wireTools, mapper := corpusNormalize(t, h)

	// Invariant 1: the wire is name-unique end to end, injected tools
	// included (an injected end_turn colliding with a client end_turn would
	// be a duplicate too).
	seen := map[string]string{}
	for _, wt := range wireTools {
		name := corpusWireName(wt)
		if name == "" {
			t.Errorf("harness %s: wire tool with no function name: %v", h.Harness, wt)
			continue
		}
		if prev, dup := seen[name]; dup {
			t.Errorf("harness %s: duplicate wire tool name %q (%s and %s) — strict upstreams reject the request outright",
				h.Harness, name, prev, corpusSourceFor(h, name))
		}
		seen[name] = h.Harness
	}

	// Invariants 2 and 3, per fixture tool. ToUpstream walks the tools array
	// in order and only APPENDS the injected end_turn/decide, so wire index i
	// is client tool i.
	for i, ct := range h.Tools {
		wire := corpusWireName(wireTools[i])
		if wire == "" {
			t.Fatalf("harness %s: wire tool %d has no name (client tool %q, source %s)", h.Harness, i, ct.Name, ct.Source)
		}
		if ForeignHarnessToolNames[wire] {
			t.Errorf("harness %s: client tool %q (source %s) reached the wire as %q, a foreign harness name — upstream raises foreign_tool_names on it",
				h.Harness, ct.Name, ct.Source, wire)
		}
		restored := mapper.RestoreName(wire)
		if restored != ct.Name {
			t.Errorf("harness %s: client tool %q (source %s) went to wire as %q but restored to %q, want the exact client name",
				h.Harness, ct.Name, ct.Source, wire, restored)
			continue
		}
		for _, shape := range []string{"delta", "message"} {
			if got := corpusRoundTripChunk(mapper, shape, wire); got != ct.Name {
				t.Errorf("harness %s: choices[].%s.tool_calls[] round-trip of %q = %q, want %q (client tool %q, source %s)",
					h.Harness, shape, wire, got, ct.Name, ct.Name, ct.Source)
			}
		}
	}

	// Invariant 4: upstream still reads the wire as first-party.
	v := ClassifyWireTools(wireTools)
	if len(v.Genuine) == 0 {
		t.Errorf("harness %s: no genuine signature tool on the wire (names %v)", h.Harness, v.Names)
	}
	if sig := WireForeignSignal(v); sig != "" {
		t.Errorf("harness %s: wire reads %q, want empty (foreign harness %v, genuine %v, tools %v)",
			h.Harness, sig, v.ForeignHarness, v.Genuine, v.Names)
	}
}

// corpusSourceFor returns the fixture's recorded registry source for one wire
// name, for failure messages on an entry that has no client tool to point at
// (e.g. the injected tools).
func corpusSourceFor(h corpusHarness, name string) string {
	for _, ct := range h.Tools {
		if ct.Name == name {
			return ct.Source
		}
	}
	if corpusInjectedTools[name] {
		return "injected signature tool (normalizeToolSchemas)"
	}
	return "unknown source"
}

// TestCorpusDualShellDedupe is the live bug this corpus work exists for, in
// isolation: opencode v2 declares BOTH `bash` and `execute`, and both map to
// run_terminal_command. The wire must stay name-unique (the second
// virtualizes to mcp__<client name>) and every wire name must still restore to
// the exact client name — no mcp__* prefix may ever leak back to a client.
func TestCorpusDualShellDedupe(t *testing.T) {
	for _, order := range [][]string{{"bash", "execute"}, {"execute", "bash"}} {
		t.Run(strings.Join(order, "+"), func(t *testing.T) {
			h := corpusHarness{
				Harness: "dual-shell",
				Repo:    "synthetic",
				Tools: []corpusTool{
					{Name: order[0], Source: "synthetic:" + order[0]},
					{Name: order[1], Source: "synthetic:" + order[1]},
				},
			}
			wireTools, mapper := corpusNormalize(t, h)

			// Both client tools map to the same official name; the later one
			// virtualizes, so the wire is exactly [official, mcp__<second>].
			wantWire := []string{"run_terminal_command", "mcp__" + order[1]}
			var gotWire []string
			for i := range h.Tools {
				gotWire = append(gotWire, corpusWireName(wireTools[i]))
			}
			if len(gotWire) != 2 || gotWire[0] != wantWire[0] || gotWire[1] != wantWire[1] {
				t.Fatalf("wire names = %v, want %v (client order %v)", gotWire, wantWire, order)
			}

			seen := map[string]bool{}
			for _, wt := range wireTools {
				name := corpusWireName(wt)
				if name != "" && seen[name] {
					t.Errorf("duplicate wire name %q in %v", name, wireNamesOf(t, wireTools))
				}
				seen[name] = true
			}

			for i, ct := range h.Tools {
				wire := corpusWireName(wireTools[i])
				if ForeignHarnessToolNames[wire] {
					t.Errorf("client tool %q reached the wire as foreign harness name %q", ct.Name, wire)
				}
				got := mapper.RestoreName(wire)
				if got != ct.Name {
					t.Errorf("RestoreName(%q) = %q, want %q (client tool %q)", wire, got, ct.Name, ct.Name)
				}
				if strings.HasPrefix(got, "mcp__") {
					t.Errorf("client tool %q restored to %q: an mcp__* virtualization leaked through to the client", ct.Name, got)
				}
				for _, shape := range []string{"delta", "message"} {
					if shapeGot := corpusRoundTripChunk(mapper, shape, wire); shapeGot != ct.Name {
						t.Errorf("choices[].%s.tool_calls[] round-trip of %q = %q, want %q", shape, wire, shapeGot, ct.Name)
					}
				}
			}

			v := ClassifyWireTools(wireTools)
			if sig := WireForeignSignal(v); sig != "" {
				t.Errorf("wire reads %q, want empty (foreign harness %v, genuine %v)", sig, v.ForeignHarness, v.Genuine)
			}
		})
	}
}

// TestCorpusFixtureIntegrity guards the generator's output shape: a fixture
// that silently goes stale, loses a harness or picks up prose matches must
// fail here rather than weaken TestCorpusToolNameMapping into a no-op.
func TestCorpusFixtureIntegrity(t *testing.T) {
	fx := loadCorpusFixture(t)
	if fx.Source != "reference/" {
		t.Errorf("fixture source = %q, want \"reference/\"", fx.Source)
	}
	if fx.GeneratedBy != "scripts/extract-tool-calls.sh" {
		t.Errorf("fixture generated_by = %q, want scripts/extract-tool-calls.sh", fx.GeneratedBy)
	}
	if len(fx.Harnesses) == 0 {
		t.Fatal("fixture has no harnesses")
	}

	// Corpus repos that produce no extractable registry must be REPORTED by
	// the generator, never emitted as an empty entry; the harness list itself
	// is checked for one of these here so a silently-dropped repo is caught.
	seenHarness := map[string]bool{}
	nameRe := regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_.:-]*$`)
	for _, h := range fx.Harnesses {
		if h.Harness == "" || h.Repo == "" {
			t.Errorf("harness entry with empty harness/repo: %+v", h)
			continue
		}
		if seenHarness[h.Harness] {
			t.Errorf("duplicate harness %q in fixture", h.Harness)
		}
		seenHarness[h.Harness] = true
		if !strings.HasPrefix(h.Repo, "agents/") && !strings.HasPrefix(h.Repo, "harnesses/") {
			t.Errorf("harness %s: repo %q is not under agents/ or harnesses/", h.Harness, h.Repo)
		}
		if len(h.Tools) == 0 {
			t.Errorf("harness %s: empty tool list — the extractor must fail loudly instead of emitting an empty harness", h.Harness)
		}
		prev := ""
		for _, ct := range h.Tools {
			if !nameRe.MatchString(ct.Name) {
				t.Errorf("harness %s: implausible extracted name %q (source %s) — the extractor matched prose or a schema property", h.Harness, ct.Name, ct.Source)
			}
			if corpusPlaceholderNames[strings.ToLower(ct.Name)] {
				t.Errorf("harness %s: placeholder name %q (source %s) — the extractor read an example/test fixture, not the registry", h.Harness, ct.Name, ct.Source)
			}
			if !strings.Contains(ct.Source, ":") || strings.HasPrefix(ct.Source, ":") {
				t.Errorf("harness %s: tool %q has no file:line source (%q)", h.Harness, ct.Name, ct.Source)
			}
			if ct.Name <= prev {
				t.Errorf("harness %s: tools are not strictly sorted/unique at %q (previous %q)", h.Harness, ct.Name, prev)
			}
			prev = ct.Name
		}
	}
}
