package convert

import (
	_ "embed"
	"encoding/json"
	"sync"
)

// cliToolsFixture is the byte-identical official CLI toolset capture also
// embedded at backend/internal/upstream/testdata/cli-tools.json. The convert
// layer owns a copy so the substitution pass stays inside the archtest matrix
// (convert may not import upstream). Regenerated by copying that file; the
// up-to-date test below fails on any drift.
//
//go:embed testdata/cli-tools.json
var cliToolsFixture []byte

var (
	canonicalToolsOnce sync.Once
	canonicalTools     []any
	canonicalToolsErr  error
)

// canonicalToolDefs returns a deep copy of the canonical CLI tool entries.
func canonicalToolDefs() ([]any, error) {
	canonicalToolsOnce.Do(func() {
		var tools []any
		if err := json.Unmarshal(cliToolsFixture, &tools); err != nil {
			canonicalToolsErr = err
			return
		}
		// Served defs carry no commit-attribution footer (fixture stays
		// byte-identical for parity); see tools_attribution.go.
		stripCommitAttribution(tools)
		canonicalTools = tools
	})
	if canonicalToolsErr != nil {
		return nil, canonicalToolsErr
	}
	raw, err := json.Marshal(canonicalTools)
	if err != nil {
		return nil, err
	}
	var out []any
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// substitutedWireNames is the set of wire names whose definitions are
// replaced with the canonical CLI entries: every rename target the proxy maps
// a foreign client tool onto, plus official names whose client schemas differ
// (glob, web_search ride verbatim but carry foreign schemas). end_turn/decide
// injections and mcp__ virtualizations are never substituted.
var substitutedWireNames = map[string]bool{
	"read_files":           true,
	"run_terminal_command": true,
	"str_replace":          true,
	"write_file":           true,
	"code_search":          true,
	"glob":                 true,
	"list_directory":       true,
	"write_todos":          true,
	"web_search":           true,
	"read_url":             true,
	"apply_patch":          true,
}

// SubstituteCanonicalDefinitions replaces substituted tool entries in
// payload["tools"] with the canonical CLI definitions, keeping the
// ToUpstream-assigned wire name. Runs after mapper.ToUpstream (names final,
// dedupe ownership settled) and after normalizeToolSchemas + the end_turn
// injection (canonical schemas must never be re-normalized, injections stay
// untouched). Entries whose wire name is not substituted (mcp__
// virtualizations, unmapped customs, end_turn/decide) keep riding verbatim.
func SubstituteCanonicalDefinitions(payload map[string]any) {
	tools, ok := payload["tools"].([]any)
	if !ok || len(tools) == 0 {
		return
	}
	defs, err := canonicalToolDefs()
	if err != nil || len(defs) == 0 {
		return // fall back to renamed-but-unsubstituted rather than fail the request
	}
	byName := make(map[string]map[string]any, len(defs))
	for _, d := range defs {
		m, ok := d.(map[string]any)
		if !ok {
			continue
		}
		fn, ok := m["function"].(map[string]any)
		if !ok {
			continue
		}
		if name, _ := fn["name"].(string); name != "" {
			byName[name] = m
		}
	}
	for i, t := range tools {
		tool, ok := t.(map[string]any)
		if !ok {
			continue
		}
		fn, ok := tool["function"].(map[string]any)
		if !ok {
			continue
		}
		name, _ := fn["name"].(string)
		if name == "" || !substitutedWireNames[name] {
			continue
		}
		def, ok := byName[name]
		if !ok {
			continue
		}
		tools[i] = def
	}
	payload["tools"] = tools
}
