// Code generated by cmd/wiregen -tools-out at upstream 276db8dff9a3d4dc323232dd8c39140cbb02538b; DO NOT EDIT.
// Sources (verbatim snapshots, never edited):
//
//	common/src/tools/constants.ts (toolNameParam, endsAgentStepParam, toolXmlName)
//
// GenericToolNames is a static pin (last upstream value at 40c75256):
// upstream deleted foreign-client-signals.ts at 0ae8779d2.
//
// Session envelope verified, no code emitted:
//
//	common/src/types/freebuff-session.ts
package convert

// ToolNameParam mirrors upstream toolNameParam: the JSON key carrying the
// tool name inside a codebuff_tool_call payload.
const ToolNameParam = "cb_tool_name"

// EndsAgentStepParam mirrors upstream endsAgentStepParam: the stop sentinel
// inside a codebuff_tool_call payload, never a tool argument.
const EndsAgentStepParam = "cb_easp"

// ToolXMLName mirrors upstream toolXmlName: the canonical XML tag for
// vendor tool calls in model output.
const ToolXMLName = "codebuff_tool_call"

// GenericToolNames is the last upstream GENERIC_TOOL_NAMES value, pinned:
// tool names we define that third-party harnesses also ship, so they carry
// no signature weight in the (upstream-removed) foreign-client gate.
// Retained for the end_turn/decide injection guard.
var GenericToolNames = map[string]bool{
	"apply_patch": true,
	"glob":        true,
	"skill":       true,
	"web_search":  true,
	"write_file":  true,
}
